# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takeoverConfig.ui'
#
# Created: Tue Dec  8 10:25:40 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(429, 404)
        Dialog.setMinimumSize(QtCore.QSize(429, 404))
        Dialog.setMaximumSize(QtCore.QSize(429, 404))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(411, 386))
        self.tabWidget.setMaximumSize(QtCore.QSize(411, 386))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.takeoverEnable = QtGui.QCheckBox(self.tab)
        self.takeoverEnable.setText(_fromUtf8(""))
        self.takeoverEnable.setObjectName(_fromUtf8("takeoverEnable"))
        self.horizontalLayout_3.addWidget(self.takeoverEnable)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.takeoverCH = QtGui.QSpinBox(self.tab)
        self.takeoverCH.setMinimumSize(QtCore.QSize(104, 27))
        self.takeoverCH.setMaximumSize(QtCore.QSize(104, 27))
        self.takeoverCH.setPrefix(_fromUtf8(""))
        self.takeoverCH.setMinimum(1)
        self.takeoverCH.setMaximum(16)
        self.takeoverCH.setObjectName(_fromUtf8("takeoverCH"))
        self.horizontalLayout.addWidget(self.takeoverCH)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.takeoverCb = QtGui.QComboBox(self.tab)
        self.takeoverCb.setObjectName(_fromUtf8("takeoverCb"))
        self.takeoverCb.addItem(_fromUtf8(""))
        self.takeoverCb.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.takeoverCb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.takeoverLe = QtGui.QLineEdit(self.tab)
        self.takeoverLe.setMinimumSize(QtCore.QSize(104, 27))
        self.takeoverLe.setMaximumSize(QtCore.QSize(104, 27))
        self.takeoverLe.setObjectName(_fromUtf8("takeoverLe"))
        self.horizontalLayout_2.addWidget(self.takeoverLe)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.saveBT = QtGui.QPushButton(self.tab)
        self.saveBT.setMinimumSize(QtCore.QSize(0, 50))
        self.saveBT.setObjectName(_fromUtf8("saveBT"))
        self.verticalLayout_2.addWidget(self.saveBT)
        self.loadBT = QtGui.QPushButton(self.tab)
        self.loadBT.setMinimumSize(QtCore.QSize(0, 50))
        self.loadBT.setObjectName(_fromUtf8("loadBT"))
        self.verticalLayout_2.addWidget(self.loadBT)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.rCChannelLabel = QtGui.QLabel(self.tab_2)
        self.rCChannelLabel.setObjectName(_fromUtf8("rCChannelLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.rCChannelLabel)
        self.rCChannelSpinBox = QtGui.QSpinBox(self.tab_2)
        self.rCChannelSpinBox.setMinimum(1)
        self.rCChannelSpinBox.setMaximum(16)
        self.rCChannelSpinBox.setProperty("value", 1)
        self.rCChannelSpinBox.setObjectName(_fromUtf8("rCChannelSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.rCChannelSpinBox)
        self.deadbandLabel = QtGui.QLabel(self.tab_2)
        self.deadbandLabel.setObjectName(_fromUtf8("deadbandLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.deadbandLabel)
        self.deadbandDoubleSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.deadbandDoubleSpinBox.setMaximum(100.0)
        self.deadbandDoubleSpinBox.setObjectName(_fromUtf8("deadbandDoubleSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.deadbandDoubleSpinBox)
        self.maxCommandLabel = QtGui.QLabel(self.tab_2)
        self.maxCommandLabel.setObjectName(_fromUtf8("maxCommandLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.maxCommandLabel)
        self.maxCommandSpinBox = QtGui.QSpinBox(self.tab_2)
        self.maxCommandSpinBox.setMaximum(500)
        self.maxCommandSpinBox.setObjectName(_fromUtf8("maxCommandSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.maxCommandSpinBox)
        self.openLoopTypeLabel = QtGui.QLabel(self.tab_2)
        self.openLoopTypeLabel.setObjectName(_fromUtf8("openLoopTypeLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.openLoopTypeLabel)
        self.openLoopTypeComboBox = QtGui.QComboBox(self.tab_2)
        self.openLoopTypeComboBox.setObjectName(_fromUtf8("openLoopTypeComboBox"))
        self.openLoopTypeComboBox.addItem(_fromUtf8(""))
        self.openLoopTypeComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.openLoopTypeComboBox)
        self.pinLabel = QtGui.QLabel(self.tab_2)
        self.pinLabel.setObjectName(_fromUtf8("pinLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pinLabel)
        self.pinLineEdit = QtGui.QLineEdit(self.tab_2)
        self.pinLineEdit.setObjectName(_fromUtf8("pinLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pinLineEdit)
        self.reverseLabel = QtGui.QLabel(self.tab_2)
        self.reverseLabel.setObjectName(_fromUtf8("reverseLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.reverseLabel)
        self.reverseCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reverseCheckBox.setObjectName(_fromUtf8("reverseCheckBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.reverseCheckBox)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.leftClibFrame = QtGui.QFrame(self.tab_2)
        self.leftClibFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.leftClibFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.leftClibFrame.setObjectName(_fromUtf8("leftClibFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.leftClibFrame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.leftSet = QtGui.QPushButton(self.leftClibFrame)
        self.leftSet.setObjectName(_fromUtf8("leftSet"))
        self.gridLayout_2.addWidget(self.leftSet, 1, 0, 1, 1)
        self.leftClib = QtGui.QPushButton(self.leftClibFrame)
        self.leftClib.setObjectName(_fromUtf8("leftClib"))
        self.gridLayout_2.addWidget(self.leftClib, 0, 0, 1, 1)
        self.leftClibSp = QtGui.QSlider(self.leftClibFrame)
        self.leftClibSp.setMinimum(1000)
        self.leftClibSp.setMaximum(2000)
        self.leftClibSp.setProperty("value", 1000)
        self.leftClibSp.setOrientation(QtCore.Qt.Horizontal)
        self.leftClibSp.setTickPosition(QtGui.QSlider.TicksBelow)
        self.leftClibSp.setTickInterval(100)
        self.leftClibSp.setObjectName(_fromUtf8("leftClibSp"))
        self.gridLayout_2.addWidget(self.leftClibSp, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.leftMin = QtGui.QLabel(self.leftClibFrame)
        self.leftMin.setObjectName(_fromUtf8("leftMin"))
        self.horizontalLayout_4.addWidget(self.leftMin)
        self.leftMid = QtGui.QLabel(self.leftClibFrame)
        self.leftMid.setObjectName(_fromUtf8("leftMid"))
        self.horizontalLayout_4.addWidget(self.leftMid)
        self.leftMax = QtGui.QLabel(self.leftClibFrame)
        self.leftMax.setObjectName(_fromUtf8("leftMax"))
        self.horizontalLayout_4.addWidget(self.leftMax)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.forwardHelpB = QtGui.QPushButton(self.leftClibFrame)
        self.forwardHelpB.setObjectName(_fromUtf8("forwardHelpB"))
        self.gridLayout_2.addWidget(self.forwardHelpB, 2, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.leftClibFrame)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.rCChannelLabel_2 = QtGui.QLabel(self.tab_3)
        self.rCChannelLabel_2.setObjectName(_fromUtf8("rCChannelLabel_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.rCChannelLabel_2)
        self.rCChannelSpinBox_2 = QtGui.QSpinBox(self.tab_3)
        self.rCChannelSpinBox_2.setMinimum(1)
        self.rCChannelSpinBox_2.setMaximum(16)
        self.rCChannelSpinBox_2.setObjectName(_fromUtf8("rCChannelSpinBox_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.rCChannelSpinBox_2)
        self.deadbandLabel_2 = QtGui.QLabel(self.tab_3)
        self.deadbandLabel_2.setObjectName(_fromUtf8("deadbandLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.deadbandLabel_2)
        self.deadbandDoubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_3)
        self.deadbandDoubleSpinBox_2.setPrefix(_fromUtf8(""))
        self.deadbandDoubleSpinBox_2.setMaximum(100.0)
        self.deadbandDoubleSpinBox_2.setObjectName(_fromUtf8("deadbandDoubleSpinBox_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.deadbandDoubleSpinBox_2)
        self.maxCommandLabel_2 = QtGui.QLabel(self.tab_3)
        self.maxCommandLabel_2.setObjectName(_fromUtf8("maxCommandLabel_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.maxCommandLabel_2)
        self.maxCommandSpinBox_2 = QtGui.QSpinBox(self.tab_3)
        self.maxCommandSpinBox_2.setMaximum(500)
        self.maxCommandSpinBox_2.setObjectName(_fromUtf8("maxCommandSpinBox_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.maxCommandSpinBox_2)
        self.openLoopTypeLabel_2 = QtGui.QLabel(self.tab_3)
        self.openLoopTypeLabel_2.setObjectName(_fromUtf8("openLoopTypeLabel_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.openLoopTypeLabel_2)
        self.openLoopTypeComboBox_2 = QtGui.QComboBox(self.tab_3)
        self.openLoopTypeComboBox_2.setObjectName(_fromUtf8("openLoopTypeComboBox_2"))
        self.openLoopTypeComboBox_2.addItem(_fromUtf8(""))
        self.openLoopTypeComboBox_2.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.openLoopTypeComboBox_2)
        self.pinLabel_2 = QtGui.QLabel(self.tab_3)
        self.pinLabel_2.setObjectName(_fromUtf8("pinLabel_2"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.pinLabel_2)
        self.pinLineEdit_2 = QtGui.QLineEdit(self.tab_3)
        self.pinLineEdit_2.setObjectName(_fromUtf8("pinLineEdit_2"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.pinLineEdit_2)
        self.reverseLabel_2 = QtGui.QLabel(self.tab_3)
        self.reverseLabel_2.setObjectName(_fromUtf8("reverseLabel_2"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.reverseLabel_2)
        self.reverseCheckBox_2 = QtGui.QCheckBox(self.tab_3)
        self.reverseCheckBox_2.setObjectName(_fromUtf8("reverseCheckBox_2"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.reverseCheckBox_2)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rightClib = QtGui.QPushButton(self.frame)
        self.rightClib.setObjectName(_fromUtf8("rightClib"))
        self.gridLayout_3.addWidget(self.rightClib, 0, 0, 1, 1)
        self.rightSet = QtGui.QPushButton(self.frame)
        self.rightSet.setObjectName(_fromUtf8("rightSet"))
        self.gridLayout_3.addWidget(self.rightSet, 1, 0, 1, 1)
        self.righClibSp = QtGui.QSlider(self.frame)
        self.righClibSp.setMinimum(1000)
        self.righClibSp.setMaximum(2000)
        self.righClibSp.setOrientation(QtCore.Qt.Horizontal)
        self.righClibSp.setTickPosition(QtGui.QSlider.TicksBelow)
        self.righClibSp.setTickInterval(100)
        self.righClibSp.setObjectName(_fromUtf8("righClibSp"))
        self.gridLayout_3.addWidget(self.righClibSp, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rightMin = QtGui.QLabel(self.frame)
        self.rightMin.setTextFormat(QtCore.Qt.AutoText)
        self.rightMin.setObjectName(_fromUtf8("rightMin"))
        self.horizontalLayout_6.addWidget(self.rightMin)
        self.rightMid = QtGui.QLabel(self.frame)
        self.rightMid.setObjectName(_fromUtf8("rightMid"))
        self.horizontalLayout_6.addWidget(self.rightMid)
        self.rightMax = QtGui.QLabel(self.frame)
        self.rightMax.setObjectName(_fromUtf8("rightMax"))
        self.horizontalLayout_6.addWidget(self.rightMax)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.turnHelpB = QtGui.QPushButton(self.frame)
        self.turnHelpB.setObjectName(_fromUtf8("turnHelpB"))
        self.gridLayout_3.addWidget(self.turnHelpB, 2, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "RiC Takeover V0.1", None))
        self.label_3.setText(_translate("Dialog", "Enable RC Takeover", None))
        self.label.setText(_translate("Dialog", "Channel of takeover: ", None))
        self.takeoverCH.setSuffix(_translate("Dialog", " CH", None))
        self.label_2.setText(_translate("Dialog", "Value of Threshold: ", None))
        self.takeoverCb.setItemText(0, _translate("Dialog", "Above", None))
        self.takeoverCb.setItemText(1, _translate("Dialog", "Below", None))
        self.saveBT.setText(_translate("Dialog", "Write", None))
        self.loadBT.setText(_translate("Dialog", "Read", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Configuration", None))
        self.rCChannelLabel.setText(_translate("Dialog", "RC channel", None))
        self.rCChannelSpinBox.setSuffix(_translate("Dialog", " CH", None))
        self.deadbandLabel.setText(_translate("Dialog", "Deadband", None))
        self.deadbandDoubleSpinBox.setSuffix(_translate("Dialog", " %", None))
        self.maxCommandLabel.setText(_translate("Dialog", "Max command", None))
        self.openLoopTypeLabel.setText(_translate("Dialog", "Open loop type", None))
        self.openLoopTypeComboBox.setItemText(0, _translate("Dialog", "RC Servo", None))
        self.openLoopTypeComboBox.setItemText(1, _translate("Dialog", "Sabertooth", None))
        self.pinLabel.setText(_translate("Dialog", "Pin", None))
        self.reverseLabel.setText(_translate("Dialog", "Reverse", None))
        self.leftSet.setText(_translate("Dialog", "Set", None))
        self.leftClib.setText(_translate("Dialog", "Calibration", None))
        self.leftMin.setText(_translate("Dialog", "Min: ", None))
        self.leftMid.setText(_translate("Dialog", "Mid: ", None))
        self.leftMax.setText(_translate("Dialog", "Max: ", None))
        self.forwardHelpB.setText(_translate("Dialog", "Calibration help", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Foward/Backward", None))
        self.rCChannelLabel_2.setText(_translate("Dialog", "RC channel", None))
        self.rCChannelSpinBox_2.setSuffix(_translate("Dialog", " CH", None))
        self.deadbandLabel_2.setText(_translate("Dialog", "Deadband", None))
        self.deadbandDoubleSpinBox_2.setSuffix(_translate("Dialog", " %", None))
        self.maxCommandLabel_2.setText(_translate("Dialog", "Max command", None))
        self.openLoopTypeLabel_2.setText(_translate("Dialog", "Open loop type", None))
        self.openLoopTypeComboBox_2.setItemText(0, _translate("Dialog", "RC Servo", None))
        self.openLoopTypeComboBox_2.setItemText(1, _translate("Dialog", "Sabertooth", None))
        self.pinLabel_2.setText(_translate("Dialog", "Pin", None))
        self.reverseLabel_2.setText(_translate("Dialog", "Reverse", None))
        self.rightClib.setText(_translate("Dialog", "Calibration", None))
        self.rightSet.setText(_translate("Dialog", "Set", None))
        self.rightMin.setText(_translate("Dialog", "Min: ", None))
        self.rightMid.setText(_translate("Dialog", "Mid: ", None))
        self.rightMax.setText(_translate("Dialog", "Max: ", None))
        self.turnHelpB.setText(_translate("Dialog", "Calibration help", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Turn", None))

