

robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
       
arm_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['rotation1_joint', 'shoulder1_joint', 'shoulder2_joint', 'rotation2_joint', 'shoulder3_joint', 'wrist_joint']
    publish_rate: 20


arm_trajectory_controller:
  type: position_velocity_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  constraints:
      goal_time: 4.0
      stopped_velocity_tolerance: 0.05
      rotation1_joint: {trajectory: 0.1, goal: 0.1}
      shoulder1_joint: {trajectory: 0.1, goal: 0.1}
      shoulder2_joint: {trajectory: 0.1, goal: 0.1}
      rotation2_joint: {trajectory: 0.1, goal: 0.1}
      shoulder3_joint: {trajectory: 0.1, goal: 0.1}
      wrist_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 5.0
  state_publish_rate:  50
  action_monitor_rate: 50



left_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 1
        init: 2048
        min: 1480
        max: 2622

right_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 2
        init: 2048
        min: 1480
        max: 2622


gripper_controller:
 type: position_controllers/GripperActionControllerTwo
 leftJoint: 'left_finger_joint'
 rightJoint: 'right_finger_joint'
 goal_tolerance: 0.005
 stalled_velocity_threshold: 0.005
 stall_timeout: 5.0
 
 
