# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 7.016223585
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 7.016223585
    has_acceleration_limits: false
    max_acceleration: 0
  rotation1_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0
  rotation2_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder1_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder2_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder3_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 3.455751915
    has_acceleration_limits: false
    max_acceleration: 0