//
// Created by tom on 07/04/16.
//

#ifndef ROBOTICAN_HARDWARE_INTERFACE_HARDWARE_DEFINE_H
#define ROBOTICAN_HARDWARE_INTERFACE_HARDWARE_DEFINE_H

#define ARMADILLO
#define ARMADILLO_ELEVATOR
#define ARMADILLO_ARM

#endif //ROBOTICAN_HARDWARE_INTERFACE_HARDWARE_DEFINE_H
